# -*- yaml modeline -*-
# vim: set ts=4 sw=4 sts=2 expandtab:
---
  - name: install required packages
    package:
      name: "{{ item }}"
      state: "present"
    with_items: "{{ rhsm_squid_proxy_packages }}"
    notify: enable squid2
    register: install_squid
    tags:
       - install
       - rhsm-squid-proxy

  - name: copy squid2 config file
    template:
      src: "{{ rhsm_squid_proxy_conf_src }}"
      dest: "{{ rhsm_squid_proxy_conf_dest }}"
      mode: "0644"
      owner: "root"
      group: "root"
      backup: "yes"
    notify: restart squid2
    tags:
       - update
       - rhsm-squid-proxy

  - name: copy squid2 sysconfig file
    template:
      src: "{{ rhsm_squid_proxy_sysconfig_src }}"
      dest: "{{ rhsm_squid_proxy_sysconfig_dest }}"
      mode: "0644"
      owner: "root"
      group: "root"
      backup: "yes"
    notify: restart squid2
    tags:
       - update
       - rhsm-squid-proxy

  - name: copy squid2 service unit file
    template:
      src: "{{ rhsm_squid_proxy_service_unit_src }}"
      dest: "{{ rhsm_squid_proxy_service_unit_dest }}"
      mode: "0644"
      owner: "root"
      group: "root"
      backup: "yes"
    notify: restart squid2
    tags:
       - update
       - rhsm-squid-proxy

  - name: make directory /var/spool/squid2
    file:
      name: "/var/spool/squid2"
      mode: "0755"
      owner: "squid"
      group: "squid"
      state: "directory"
    register: make_squid_directory
    tags:
       - update
       - rhsm-squid-proxy

  - name: chcon /var/spool/squid2
    shell: "chcon -R --reference=/var/spool/squid /var/spool/squid2"
    when: make_squid_directory.changed
    tags:
       - update
       - rhsm-squid-proxy

  - sefcontext:
      target: "/var/spool/squid2(/.*)?"
      setype: squid_cache_t
      state: present
    when: make_squid_directory.changed
    tags:
       - update
       - rhsm-squid-proxy

  - name: populate cache directory
    shell: "squid -z -f /etc/squid/squid2.conf"
    when: install_squid.changed
    tags:
       - update
       - rhsm-squid-proxy
